### PR TITLE
Update Vocalink data sets to version v640 valid as of 12/10/2020

### PR DESCRIPTION
**Pull request by solanki-das**

### CODE REVIEW

**Review by franciscocardoso — CHANGES_REQUESTED** [review]
Hi @solanki-das,

Thanks for the PR.
I have a couple of request for you:

1. Please remove all the DS_Store files that are being added by your PR;

1. Please squash both commits into one and update the commit message to match the latest ones, something like:
```
Update Vocalink data sets to versions valid as of dd/mm/yyy
```

**Comment by solanki-das** [comment]
Hi Francisco,

Should I fork a new branch and commit the changes there?

Regards
Solanki Das

**Comment by franciscocardoso** [comment]
You can fix it on this branch and push it again.

**Comment by solanki-das** [comment]
Hi Francisco,

I was not able to revert back the changes so I created a new branch – “Update Vocalink data sets to v640 valid as of 12/10/2020<https://github.com/uphold/uk-modulus-checking/pull/23>”.

Could you please ignore and delete the previous branch and consider this latest branch.

Regards
Solanki Das

**Comment by franciscocardoso** [comment]
Deprecated by https://github.com/uphold/uk-modulus-checking/pull/23.

**Pull request closed without merging**
